apiVersion: v1
kind: Service
metadata: 
  name: app-service
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 10
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: damiruggi/app:1.0.0
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
